//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_InventorySystem : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean OpenUI
        {
            get
            {
                return SteamVR_Actions.inventorySystem_OpenUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean PickUpItem
        {
            get
            {
                return SteamVR_Actions.inventorySystem_PickUpItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractWithUI
        {
            get
            {
                return SteamVR_Actions.inventorySystem_InteractWithUI;
            }
        }
    }
}
